# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'account.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Rantang import Ui_MainWindow2
import pymysql

class Ui_MainWindow(object):
    def koneksi(self):
        con = pymysql.connect(db='rantang', user='root', password='', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        if(cur):
            self.messagebox("Koneksi", "Koneksi Berhasil")
        else:
            self.messagebox("Koneksi", "Koneksi Gagal")

    def messagebox(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

    def warning(self,title,message):
        mess=QtWidgets.QMessageBox()

        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.stackedWidget.setObjectName("stackedWidget")
        self.Register = QtWidgets.QWidget()
        self.Register.setObjectName("Register")
        self.frame = QtWidgets.QFrame(self.Register)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(-1, -1, 490, 611))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label = QtWidgets.QLabel(self.frame_9)
        self.label.setGeometry(QtCore.QRect(0, -2, 490, 611))
        self.label.setStyleSheet("image: url(:/Logo/Image/tool/logo + back-01.png);\n"
"background-color: rgb(255, 204, 51);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setGeometry(QtCore.QRect(489, -1, 310, 611))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.alreadyhaveaccount = QtWidgets.QLabel(self.frame_10)
        self.alreadyhaveaccount.setGeometry(QtCore.QRect(30, 100, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.alreadyhaveaccount.setFont(font)
        self.alreadyhaveaccount.setObjectName("alreadyhaveaccount")
        self.getstarted = QtWidgets.QLabel(self.frame_10)
        self.getstarted.setGeometry(QtCore.QRect(26, 50, 271, 41))
        self.getstarted.setStyleSheet("font: 75 24pt \"Rockwell\";")
        self.getstarted.setObjectName("getstarted")
        self.emailRegister = QtWidgets.QLabel(self.frame_10)
        self.emailRegister.setGeometry(QtCore.QRect(30, 190, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.emailRegister.setFont(font)
        self.emailRegister.setObjectName("emailRegister")
        self.NamaLengkap = QtWidgets.QLabel(self.frame_10)
        self.NamaLengkap.setGeometry(QtCore.QRect(30, 260, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.NamaLengkap.setFont(font)
        self.NamaLengkap.setObjectName("NamaLengkap")
        self.Alamat = QtWidgets.QLabel(self.frame_10)
        self.Alamat.setGeometry(QtCore.QRect(30, 340, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.Alamat.setFont(font)
        self.Alamat.setObjectName("Alamat")
        self.Password = QtWidgets.QLabel(self.frame_10)
        self.Password.setGeometry(QtCore.QRect(30, 410, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.Password.setFont(font)
        self.Password.setObjectName("Password")
        self.kolomEmail = QtWidgets.QLineEdit(self.frame_10)
        self.kolomEmail.setGeometry(QtCore.QRect(30, 210, 241, 41))
        self.kolomEmail.setObjectName("kolomEmail")
        self.kolomNamaLengkap = QtWidgets.QLineEdit(self.frame_10)
        self.kolomNamaLengkap.setGeometry(QtCore.QRect(30, 290, 241, 41))
        self.kolomNamaLengkap.setObjectName("kolomNamaLengkap")
        self.KolomAlamat = QtWidgets.QLineEdit(self.frame_10)
        self.KolomAlamat.setGeometry(QtCore.QRect(30, 360, 241, 41))
        self.KolomAlamat.setObjectName("KolomAlamat")
        self.KolomPassword = QtWidgets.QLineEdit(self.frame_10)
        self.KolomPassword.setGeometry(QtCore.QRect(30, 430, 241, 41))
        self.KolomPassword.setObjectName("KolomPassword")
        self.registerbutton = QtWidgets.QPushButton(self.frame_10)

        self.registerbutton.clicked.connect(self.submit)

        self.registerbutton.setGeometry(QtCore.QRect(110, 490, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.registerbutton.setFont(font)
        self.registerbutton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(235, 89, 110);}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91,90,90);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.registerbutton.setObjectName("registerbutton")
        self.loginbt = QtWidgets.QPushButton(self.frame_10)

        self.loginbt.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.Login))

        self.loginbt.setGeometry(QtCore.QRect(170, 100, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.loginbt.setFont(font)
        self.loginbt.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    color:  rgb(235, 89, 110);\n"
"    background-color: rgba(0,0,0,0);}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91,90,90);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.loginbt.setObjectName("loginbt")
        self.stackedWidget.addWidget(self.Register)
        self.Login = QtWidgets.QWidget()
        self.Login.setObjectName("Login")
        self.frame_3 = QtWidgets.QFrame(self.Login)
        self.frame_3.setGeometry(QtCore.QRect(0, -10, 800, 611))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_11 = QtWidgets.QFrame(self.frame_3)
        self.frame_11.setGeometry(QtCore.QRect(0, 10, 800, 600))
        self.frame_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setGeometry(QtCore.QRect(-1, -11, 490, 621))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_2 = QtWidgets.QLabel(self.frame_12)
        self.label_2.setGeometry(QtCore.QRect(0, 8, 490, 601))
        self.label_2.setStyleSheet("background-color: rgb(255, 204, 51);\n"
"image: url(:/Logo/Image/tool/logo + back-01.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setGeometry(QtCore.QRect(489, -11, 310, 621))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.pleaseLogin = QtWidgets.QLabel(self.frame_13)
        self.pleaseLogin.setGeometry(QtCore.QRect(30, 100, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.pleaseLogin.setFont(font)
        self.pleaseLogin.setObjectName("pleaseLogin")
        self.getStarted = QtWidgets.QLabel(self.frame_13)
        self.getStarted.setGeometry(QtCore.QRect(26, 50, 281, 41))
        self.getStarted.setStyleSheet("font: 75 22pt \"Rockwell\";")
        self.getStarted.setObjectName("getStarted")
        self.emailLogin = QtWidgets.QLabel(self.frame_13)
        self.emailLogin.setGeometry(QtCore.QRect(30, 190, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.emailLogin.setFont(font)
        self.emailLogin.setObjectName("emailLogin")
        self.passwordLogin = QtWidgets.QLabel(self.frame_13)
        self.passwordLogin.setGeometry(QtCore.QRect(30, 270, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.passwordLogin.setFont(font)
        self.passwordLogin.setObjectName("passwordLogin")
        self.kolomemaillogin = QtWidgets.QLineEdit(self.frame_13)
        self.kolomemaillogin.setGeometry(QtCore.QRect(30, 210, 241, 41))
        self.kolomemaillogin.setObjectName("kolomemaillogin")
        self.kolompasswordlogin = QtWidgets.QLineEdit(self.frame_13)
        self.kolompasswordlogin.setGeometry(QtCore.QRect(30, 290, 241, 41))
        self.kolompasswordlogin.setObjectName("kolompasswordlogin")
        self.LoginButton = QtWidgets.QPushButton(self.frame_13)

        self.LoginButton.clicked.connect(self.login)

        self.LoginButton.setGeometry(QtCore.QRect(110, 350, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LoginButton.setFont(font)
        self.LoginButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(235, 89, 110);}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91,90,90);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.LoginButton.setObjectName("LoginButton")
        self.dontthaveAccount = QtWidgets.QLabel(self.frame_13)
        self.dontthaveAccount.setGeometry(QtCore.QRect(30, 390, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.dontthaveAccount.setFont(font)
        self.dontthaveAccount.setObjectName("dontthaveAccount")
        self.Registerbt = QtWidgets.QPushButton(self.frame_13)
        self.Registerbt.setGeometry(QtCore.QRect(170, 390, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Registerbt.setFont(font)
        self.Registerbt.setStyleSheet("\n"
"QPushButton {\n"
"    border: none;\n"
"    color: rgb(235, 89, 110);\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91,90,90);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.Registerbt.setObjectName("Registerbt")
        self.stackedWidget.addWidget(self.Login)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.alreadyhaveaccount.setText(_translate("MainWindow", "Already have an account ? "))
        self.getstarted.setText(_translate("MainWindow", "Let\'s Get Started"))
        self.emailRegister.setText(_translate("MainWindow", "E Mail"))
        self.NamaLengkap.setText(_translate("MainWindow", "Nama Lengkap"))
        self.Alamat.setText(_translate("MainWindow", "Alamat"))
        self.Password.setText(_translate("MainWindow", "Password"))
        self.registerbutton.setText(_translate("MainWindow", "Register"))
        self.loginbt.setText(_translate("MainWindow", "Login"))
        self.pleaseLogin.setText(_translate("MainWindow", "Please Login in to your account"))
        self.getStarted.setText(_translate("MainWindow", "Welcome to Rantang"))
        self.emailLogin.setText(_translate("MainWindow", "E Mail"))
        self.passwordLogin.setText(_translate("MainWindow", "Password"))
        self.LoginButton.setText(_translate("MainWindow", "Login"))
        self.dontthaveAccount.setText(_translate("MainWindow", "Don\'t  have an account ? "))
        self.Registerbt.setText(_translate("MainWindow", "Register"))

    def submit(self):
        email = self.kolomEmail.text()
        namalengkap = self.kolomNamaLengkap.text()
        alamat = self.KolomAlamat.text()
        password = self.KolomPassword.text()


        insert = (email, namalengkap, alamat, password)

        print(insert)
        if self.kolomEmail.text() and self.kolomNamaLengkap.text()\
                and self.KolomAlamat.text() and self.KolomPassword.text():

            con = pymysql.connect(db='rantang', user='root', password='', host='localhost', port=3306, autocommit=True)
            cur = con.cursor()
            sql = "INSERT INTO registrasi(email, namalengkap, alamat, password)" + "VALUES" + str(insert)
            data = cur.execute(sql)
            ui.messagebox("SUKSES", "Data Berhasil di Submit")
        else:
            ui.messagebox("GAGAL", "Mohon lengkapi form ")

    def login(self):
        email = self.kolomemaillogin.text()
        password = self.kolompasswordlogin.text()
        con = pymysql.connect(db='rantang', user='root', password='', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        query="select * from registrasi where email=%s and password=%s"
        data =cur.execute(query, (email, password))

        if(len(cur.fetchall())>0):
            self.messagebox("Berhasil", "Anda telah Login")
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_MainWindow2()
            self.ui.setupUi(self.window)
            self.window.show()
        else:
            self.messagebox("GAGAL", "Username atau Password Salah ! ")

import Resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
